name: SimpleVeinMining
version: '${project.version}'
main: simplexity.simpleveinmining.SimpleVeinMining
api-version: '1.20'
permissions:
  veinmining.mining:
    default: op
    description: vein mining